# Lab1

# Task 1

In [69]:
myList = [10,20,3,4,23,43]
evenNums=list(filter(lambda x:x%2==0, myList))
evenResult=list(map(lambda x:x**3, evenNums))
evenResult
oddNums=list(filter(lambda x:x%2!=0, myList))
oddResult=list(map(lambda x:x**2, oddNums))
oddResult
Result = evenResult+oddResult
SortedResult = sorted(Result)
SortedResult

[9, 64, 529, 1000, 1849, 8000]

# Task 2

In [50]:
Products = {}

for i in range(0, 6):
    name = input("Enter the product name: ") #user input
    cat = input("Enter product category: ")
    price = float(input("Enter price: "))

    Products[i] = {
        "Prod_Name": name,
        "Prod_Category": cat,
        "price": price
    }
    minProduct = min(Products.items(), key=lambda item: item[1]["price"])
    print(minProduct)
    maxProduct = max(Products.items(), key=lambda item: item[1]["price"])
    print(maxProduct)
    sorted_products = sorted(Products.items(), key=lambda item: item[1]["price"])
    print(sorted_products)

KeyboardInterrupt: Interrupted by user

# Task 3

In [ ]:
import functools
List = [1,2,3,4,45,3,12,34,23,54]
evenNums=list(filter(lambda x:x%2==0, List))
evenResult=list(map(lambda x:x**2, evenNums))
prod = functools.reduce(lambda x,y: x+y, evenResult)
print(prod)

# Task 4

# Task 5

In [58]:
import numpy as np
random_matrix = np.random.rand(6, 4)
print(random_matrix)
random_matrix.shape, random_matrix.size, random_matrix.dtype
colMean = np.mean(random_matrix, axis=0)
print(colMean)
rowMax = np.max(random_matrix, axis=1)
print(rowMax)
max_idx = int(np.argmax(random_matrix))
print(max_idx)

[[0.44128819 0.58669671 0.23863809 0.81385999]
 [0.42656686 0.80543679 0.83601459 0.56423137]
 [0.2504971  0.5447208  0.28399161 0.13009686]
 [0.071029   0.11785051 0.1661225  0.56563147]
 [0.95875386 0.14731977 0.38554391 0.50284405]
 [0.49716097 0.91601855 0.19436252 0.2454953 ]]
[0.44088266 0.51967385 0.35077887 0.47035984]
[0.81385999 0.83601459 0.5447208  0.56563147 0.95875386 0.91601855]
16


# Task 6

In [68]:
import numpy as np

matrix = np.array([
    [1, 67, 34],
    [2, 83, 34]
])
averageScores = np.mean(matrix, axis=1)
print(averageScores)
Ranking = np.argsort(matrix)
print(Ranking)

[34.         39.66666667]
[[0 2 1]
 [0 2 1]]


# Task 7

In [3]:
import numpy as np
random_matrix = np.random.rand(100, 3)
Colmin = np.max(random_matrix, axis=0)
Colmax = np.min(random_matrix, axis=0)
normalized_Data = (random_matrix - Colmin) / (Colmax - Colmin)
variances = normalized_Data.var(axis=0)
highestVarColIndex = np.argmax(variances)
print(highestVarColIndex)


0


# Task 8